// src/pages/TiffinPlans/dummyTiffinPlans.js
//
// Dummy data just so you can preview the page. Replace this with your real
// API call once you wire it back up — the shape below matches your backend
// TiffinPlan fields exactly (id, providerId, planName, validityDays,
// offersBreakfast/Lunch/Dinner, pricePerBreakfast/Lunch/Dinner, maxCapacity,
// activeSubscribers, isActive, createdAt).

const dummyTiffinPlans = [
  {
    id: 1,
    providerId: 101,
    planName: "Monthly Veg Combo",
    validityDays: 30,
    offersBreakfast: true,
    offersLunch: true,
    offersDinner: true,
    pricePerBreakfast: 60,
    pricePerLunch: 110,
    pricePerDinner: 100,
    maxCapacity: 50,
    activeSubscribers: 32,
    isActive: true,
    createdAt: "2026-04-12T09:00:00",
  },
  {
    id: 2,
    providerId: 101,
    planName: "Lunch Only Plan",
    validityDays: 15,
    offersBreakfast: false,
    offersLunch: true,
    offersDinner: false,
    pricePerBreakfast: 0,
    pricePerLunch: 120,
    pricePerDinner: 0,
    maxCapacity: 30,
    activeSubscribers: 18,
    isActive: true,
    createdAt: "2026-05-01T09:00:00",
  },
  {
    id: 3,
    providerId: 101,
    planName: "Weekend Dinner Special",
    validityDays: 7,
    offersBreakfast: false,
    offersLunch: false,
    offersDinner: true,
    pricePerBreakfast: 0,
    pricePerLunch: 0,
    pricePerDinner: 150,
    maxCapacity: 20,
    activeSubscribers: 4,
    isActive: false,
    createdAt: "2026-05-15T09:00:00",
  },
  {
    id: 4,
    providerId: 101,
    planName: "Breakfast & Lunch Bundle",
    validityDays: 30,
    offersBreakfast: true,
    offersLunch: true,
    offersDinner: false,
    pricePerBreakfast: 55,
    pricePerLunch: 105,
    pricePerDinner: 0,
    maxCapacity: 40,
    activeSubscribers: 27,
    isActive: true,
    createdAt: "2026-06-02T09:00:00",
  },
  {
    id: 5,
    providerId: 101,
    planName: "Full Day Premium",
    validityDays: 30,
    offersBreakfast: true,
    offersLunch: true,
    offersDinner: true,
    pricePerBreakfast: 80,
    pricePerLunch: 150,
    pricePerDinner: 140,
    maxCapacity: 25,
    activeSubscribers: 25,
    isActive: true,
    createdAt: "2026-06-20T09:00:00",
  },
  {
    id: 6,
    providerId: 101,
    planName: "Trial Pack",
    validityDays: 3,
    offersBreakfast: false,
    offersLunch: true,
    offersDinner: true,
    pricePerBreakfast: 0,
    pricePerLunch: 100,
    pricePerDinner: 95,
    maxCapacity: 15,
    activeSubscribers: 2,
    isActive: false,
    createdAt: "2026-06-28T09:00:00",
  },
];

export default dummyTiffinPlans;
